# Generated by Django 4.1.5 on 2023-02-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('echelon', '0001_initial'),
        ('accounts', '0002_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('term', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=150)),
                ('classes', models.ManyToManyField(to='echelon.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=150)),
                ('class_fk', models.ManyToManyField(blank=True, to='echelon.class')),
                ('exam_master', models.ManyToManyField(blank=True, to='assessment.exammaster')),
                ('room', models.ManyToManyField(blank=True, to='echelon.room')),
                ('subject', models.ManyToManyField(blank=True, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.IntegerField()),
                ('test_2', models.IntegerField()),
                ('test_3', models.IntegerField()),
                ('test_4', models.IntegerField()),
                ('total_mark', models.IntegerField()),
                ('average_mark', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_processed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=150)),
                ('exam_result', models.ManyToManyField(blank=True, to='assessment.examresult')),
                ('grade', models.ManyToManyField(blank=True, to='grade.grademaster')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='exammaster',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.examtype'),
        ),
    ]
