# Generated by Django 4.1.5 on 2023-02-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0011_rename_parent_student_parents'),
        ('assessment', '0002_exammaster_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaster',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='organisation',
        ),
        migrations.AddField(
            model_name='exammaster',
            name='exam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.examtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtype',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation'),
            preserve_default=False,
        ),
    ]
