# Generated by Django 4.1.5 on 2023-02-26 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0006_rename_test_1_score_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='test',
            new_name='test_score',
        ),
    ]
