# Generated by Django 4.1.5 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0007_rename_test_score_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='average_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
