# Generated by Django 4.1.5 on 2023-02-28 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0001_initial'),
        ('assessment', '0008_alter_score_average_mark_alter_score_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echelon.term'),
        ),
    ]
