# Generated by Django 4.1.5 on 2023-02-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('echelon', '0001_initial'),
        ('accounts', '0002_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('point', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='echelon.level')),
                ('organisation',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='GradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_from', models.IntegerField()),
                ('marks_to', models.IntegerField()),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('class_fk', models.ManyToManyField(blank=True, to='echelon.class')),
                ('grade',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grade.grademaster')),
                ('subject', models.ManyToManyField(blank=True, to='subject.subject')),
            ],
        ),
    ]
