# Generated by Django 4.1.5 on 2023-02-19 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('msg_receiver',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver',
                                   to=settings.AUTH_USER_MODEL)),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender',
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
