# Generated by Django 4.1.5 on 2023-01-18 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission', models.ManyToManyField(blank=True, to='accounts.permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.ManyToManyField(blank=True, to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_address', models.TextField(blank=True, null=True)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('fax', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation', models.ManyToManyField(blank=True, to='accounts.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_type',
            field=models.ManyToManyField(blank=True, to='accounts.organisationtype'),
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
                ('organisation', models.ManyToManyField(blank=True, to='accounts.organisation')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission', verbose_name='user permissions')),
                ('user_type', models.ManyToManyField(blank=True, to='accounts.usertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(null=True, upload_to='teachers_photos/')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='users_photos/')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='headmasters_photos/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='headmaster_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
    ]
