# Generated by Django 4.1.5 on 2023-01-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('echelon', '0001_initial'),
        ('subject', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_class',
            field=models.ManyToManyField(to='echelon.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='subject.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='base_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='class_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student',
                                    to='echelon.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='accounts.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='subject.subject'),
        ),
    ]
