# Generated by Django 4.1.5 on 2023-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_baseuser_is_staff_alter_baseuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organisation',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.usertype'),
        ),
    ]
