# Generated by Django 4.1.5 on 2023-01-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
