# Generated by Django 4.1.5 on 2023-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_delete_permissions_alter_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
