# Generated by Django 4.1.5 on 2023-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_baseuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, to='accounts.user'),
        ),
    ]
