# Generated by Django 4.1.5 on 2023-01-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_baseuser_organisation_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organisation',
            field=models.ManyToManyField(to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.ManyToManyField(to='accounts.usertype'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
