# Generated by Django 4.1.5 on 2023-01-24 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_alter_baseuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursar',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='bursars_photos/')),
                ('base_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursar_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='headteachers_photos/')),
                ('base_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='head_teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='librarians_photos/')),
                ('base_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='librarian_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='parents_photos/')),
                ('base_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='accounts.parent'),
        ),
    ]
