# Generated by Django 4.1.7 on 2023-03-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_alter_student_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='organisation',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='organisation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='accounts.organisation'),
        ),
    ]
