# Generated by Django 4.1.7 on 2023-03-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_remove_baseuser_organisation_baseuser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organisation',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='accounts.organisation'),
        ),
    ]
