# Generated by Django 4.1.5 on 2023-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_remove_baseuser_user_type_baseuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
