# Generated by Django 4.1.5 on 2023-02-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_alter_organisationprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_1', models.CharField(max_length=15, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='headteachers_photos/')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.RemoveField(
            model_name='headteacher',
            name='base_user',
        ),
        migrations.RemoveField(
            model_name='headteacher',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='base_user',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='base_user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='base_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='base_user',
        ),
        migrations.DeleteModel(
            name='Bursar',
        ),
        migrations.DeleteModel(
            name='HeadTeacher',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='accounts.user'),
        ),
    ]
