# Generated by Django 4.1.5 on 2023-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_user_remove_headteacher_base_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
