# Generated by Django 4.1.5 on 2023-02-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_alter_user_telephone_1_alter_user_telephone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usertype'),
        ),
    ]
