# Generated by Django 4.1.5 on 2023-02-04 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parents',
        ),
    ]
