# Generated by Django 4.1.5 on 2023-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='class_fk',
        ),
        migrations.AddField(
            model_name='room',
            name='class_fk',
            field=models.ManyToManyField(null=True, related_name='class_fk', to='echelon.class'),
        ),
    ]
