# Generated by Django 4.1.5 on 2023-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starts_on', models.DateTimeField(auto_now=True)),
                ('ends_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
