# Generated by Django 4.1.5 on 2023-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0002_remove_room_class_fk_room_class_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='class_fk',
            field=models.ManyToManyField(related_name='class_fk', to='echelon.class'),
        ),
    ]
