# Generated by Django 4.1.5 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0002_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
