# Generated by Django 4.1.7 on 2023-03-06 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0003_alter_room_class_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
