# Generated by Django 4.1.5 on 2023-02-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('echelon', '0003_term_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='ends_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='starts_on',
            field=models.DateField(),
        ),
    ]
