# Generated by Django 4.1.5 on 2023-02-19 08:14

import django.utils.timezone
from django.db import migrations, models

import assessment.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('echelon', '0001_initial'),
        ('subject', '0001_initial'),
        ('accounts', '0002_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                        verbose_name=assessment.models.Exam)),
                ('timestamp_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name=assessment.models.Exam)),
                ('time_from', models.CharField(max_length=20, unique=True)),
                ('time_to', models.CharField(max_length=20, unique=True)),
                ('hour_from', models.IntegerField()),
                ('minute_from', models.IntegerField()),
                ('meridian_from', models.CharField(max_length=3, unique=True)),
                ('hour_to', models.IntegerField()),
                ('minute_to', models.IntegerField()),
                ('meridian_to', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_fk', models.ManyToManyField(blank=True, to='echelon.class')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation', models.ManyToManyField(blank=True, to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_slot', models.ManyToManyField(blank=True, to='timetable.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_fk', models.ManyToManyField(blank=True, to='echelon.class')),
                ('exam', models.ManyToManyField(blank=True, to='assessment.exammaster')),
                ('subject', models.ManyToManyField(blank=True, to='subject.subject')),
                ('time_slot', models.ManyToManyField(blank=True, to='timetable.timeslot')),
                ('timetable_type',
                 models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE,
                                   to='timetable.timetabletype')),
            ],
        ),
    ]
