# Generated by Django 4.1.5 on 2023-01-23 05:56

import assessment.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('echelon', '0001_initial'),
        ('assessment', '0001_initial'),
        ('subject', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                        verbose_name=assessment.models.ExamMaster)),
                ('timestamp_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name=assessment.models.ExamMaster)),
                ('time_from', models.CharField(max_length=20, unique=True)),
                ('time_to', models.CharField(max_length=20, unique=True)),
                ('hour_from', models.IntegerField()),
                ('minute_from', models.IntegerField()),
                ('meridian_from', models.CharField(max_length=3, unique=True)),
                ('hour_to', models.IntegerField()),
                ('minute_to', models.IntegerField()),
                ('meridian_to', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation', models.ManyToManyField(blank=True, to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('year', models.IntegerField()),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_fk', models.ManyToManyField(blank=True, to='echelon.class')),
                ('exam', models.ManyToManyField(blank=True, to='assessment.exammaster')),
                ('timetable_type', models.ManyToManyField(blank=True, to='timetable.timetabletype')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                             verbose_name=assessment.models.ExamMaster)),
                ('timestamp_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                        verbose_name=assessment.models.ExamMaster)),
                ('timestamp_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name=assessment.models.ExamMaster)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ManyToManyField(blank=True, to='subject.subject')),
                ('time_slot', models.ManyToManyField(blank=True, to='timetable.timeslot')),
                ('timetable_record', models.ManyToManyField(blank=True, to='timetable.timetablerecord')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timetable_record',
            field=models.ManyToManyField(blank=True, to='timetable.timetablerecord'),
        ),
    ]
