# Generated by Django 4.1.5 on 2023-02-17 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0003_remove_exammaster_exam_type_and_more'),
        ('echelon', '0004_alter_term_ends_on_alter_term_starts_on'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='timetable_record',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timestamp_from',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timestamp_to',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timetable_record',
        ),
        migrations.RemoveField(
            model_name='timetablerecord',
            name='class_fk',
        ),
        migrations.RemoveField(
            model_name='timetablerecord',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='timetablerecord',
            name='timetable_type',
        ),
        migrations.RemoveField(
            model_name='timetablerecord',
            name='year',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='class_fk',
            field=models.ManyToManyField(blank=True, to='echelon.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_fk',
            field=models.ManyToManyField(blank=True, to='echelon.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='exam',
            field=models.ManyToManyField(blank=True, to='assessment.exammaster'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='timetable_type',
            field=models.ManyToManyField(blank=True, to='timetable.timetabletype'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.IntegerField(default=0000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetablerecord',
            name='time_slot',
            field=models.ManyToManyField(blank=True, to='timetable.timeslot'),
        ),
    ]
