# Generated by Django 4.1.5 on 2023-02-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0002_remove_timeslot_timetable_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='timetable_type',
        ),
        migrations.AddField(
            model_name='timetable',
            name='timetable_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='timetable.timetabletype'),
        ),
    ]
