# Generated by Django 4.1.5 on 2023-03-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0011_alter_result_average_score_alter_result_promotion_and_more'),
        ('timetable', '0002_remove_timetable_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='exam',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='timetable.timetabletype'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='exam',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='assessment.exam'),
        ),
    ]
