# Generated by Django 4.1.5 on 2023-03-04 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0004_timetable_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='class_fk',
        ),
    ]
