# Generated by Django 4.1.5 on 2023-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0007_alter_timeslot_timestamp_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timestamp_from',
            field=models.TimeField(blank=True, default=1677929122.201004, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='timestamp_to',
            field=models.TimeField(blank=True, default=1677929122.2010224, null=True),
        ),
    ]
