# Generated by Django 4.1.5 on 2023-03-04 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0010_alter_timeslot_meridian_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablerecord',
            name='day_of_week',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
