# Generated by Django 4.1.5 on 2023-03-04 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0011_timetablerecord_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetablerecord',
            old_name='title',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='timetablerecord',
            name='description',
        ),
    ]
