# Generated by Django 4.1.5 on 2023-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0012_rename_title_timetablerecord_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablerecord',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
