# Generated by Django 4.1.5 on 2023-03-04 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0014_remove_timetablerecord_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablerecord',
            name='time_slot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='timetable.timeslot'),
        ),
    ]
