# Generated by Django 4.1.5 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subject', '0002_subject_abbreviated_name_subject_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='maximum_mark',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
